### ISSUE TITLE
Cannot achieve good accuracy after training on COCO dataset

### ISSUE THREAD

**Issue by JohnPekl** [ChenhongyiYang/QueryDet-PyTorch#32]
I am trying to retrain your network. I set up a training environment following issue #25 . My computer has two GPU GeForce RTX 3090, 24G. I reduce batch size from your set up (16) to 8 in [train_mp.yaml](https://github.com/ChenhongyiYang/QueryDet-PyTorch/blob/main/models/querydet/configs/coco/train_mp.yaml) as follows.

```
SOLVER:
  # 3x
  # STEPS: (210000, 250000)
  # MAX_ITER: 270000

  # 1x
  BASE_LR: 0.005
  STEPS: (120000, 160000)
  MAX_ITER: 180000
  IMS_PER_BATCH: 8
```
After training, I load model_final.pth (change in [test.yaml](https://github.com/ChenhongyiYang/QueryDet-PyTorch/blob/main/models/querydet/configs/coco/test.yaml)). [The weight is uploaded here [GoogleDriver](https://drive.google.com/file/d/15LPaHmxa4YlmsuepuAa40HTsjfgSmAal/view?usp=sharing). Training log is [here](https://drive.google.com/file/d/1O94k6BWAGSpoXBDR-B4zHhvVDd0XP0OX/view?usp=sharing).]

```
MODEL:
  META_ARCHITECTURE: "RetinaNetQueryDet"
  WEIGHTS: "../default_dir/model_final.pth"
```

I then run [infer_coco.py.](https://github.com/ChenhongyiYang/QueryDet-PyTorch/blob/main/infer_coco.py), and use an image in COCO dataset (`datasets/coco/test2017/000000000001.jpg`). It gives me a weird result.

Do you know what went wrong?

![image](https://user-images.githubusercontent.com/15703029/176614984-f77c912c-3e54-45ab-99bc-54293ee78c20.png)
